salesforge-backup-mdapi/objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Last_Service_Date__c</fullName>
        <label>Last Service Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Make__c</fullName>
        <label>Make</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Mileage__c</fullName>
        <label>Mileage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Model__c</fullName>
        <label>Model</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                </value>
                <value>
                    <fullName>In Maintenance</fullName>
                </value>
                <value>
                    <fullName>Retired</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>100</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

force-app/main/default/classes/FleetService.cls
public with sharing class FleetService {

    public static List<Vehicle__c> getVehiclesDueForService(
        Integer mileageThreshold
    ) {

        return [
            SELECT Id,
                   VIN__c,
                   Make__c,
                   Model__c,
                   Mileage__c,
                   Status__c,
                   Last_Service_Date__c
            FROM Vehicle__c
            WHERE Status__c = 'Active'
            AND Mileage__c > :mileageThreshold
        ];
    }
}